language: python
python:
- '2.7'
- '3.6'
install:
- pip install .
- pip install coveralls
- pip install pykdtree
- pip install matplotlib
script: coverage run --source=trollsched setup.py test
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran python-tk python3-tk tk-dev
after_success: coveralls
